In [1]:
from tqdm import tqdm

In [2]:
from imblearn.combine import *
from imblearn.over_sampling import *
from imblearn.under_sampling import *

In [3]:
import numpy as np
import scipy as sp
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.stats.api as sms
import sklearn as sk
import datetime as dt

# import matplotlib as mpl
# mpl.use('Agg')
# import matplotlib.pylab as plt
# from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline
from sklearn.preprocessing import Imputer
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
import seaborn as sns
sns.set()
sns.set_style("whitegrid")
sns.set_color_codes()
''
import warnings

warnings.filterwarnings('ignore')

In [4]:
# train 
detail_train = pd.read_csv('./coupon_data_project2/coupon_detail_train_translated_en.csv', parse_dates=['I_DATE'])
visit_train = pd.read_csv('./coupon_data_project2/coupon_visit_train.csv', parse_dates=['I_DATE'])

area_train = pd.read_csv('./coupon_data_project2/coupon_area_train_translated_en.csv')
coupon_list_train = pd.read_csv('./coupon_data_project2/coupon_list_train_translated_en.csv', parse_dates=['DISPFROM', 'DISPEND', 'VALIDFROM', 'VALIDEND'])

# base data
location = pd.read_csv('./coupon_data_project2/train_location.csv')
user_list = pd.read_csv('./coupon_data_project2/user_list_translated_en.csv', parse_dates=['WITHDRAW_DATE', 'REG_DATE'])

# test data
area_test = pd.read_csv('./coupon_data_project2/test_location.csv')
coupon_list_test = pd.read_csv('./coupon_data_project2/coupon_list_test_translated_en.csv', parse_dates=['DISPFROM', 'DISPEND', 'VALIDFROM', 'VALIDEND'])

# submisiion
submission = pd.read_csv('./coupon_data_project2/sample_submission.csv')

In [5]:
# 테이블 현황 파악을 위한 함수 
def summary_table(table):
    df = pd.DataFrame()
    for i in table.columns:
        name = i
        dtype = table[i].dtype.name
        null = table[i].isnull().sum()
        act = table.shape[0] - null
        unique = len(table[i].unique())
        data = {'name': name, 'dtype': dtype, 'null': null, 'act': act, 'unique': unique}
        df = df.append(data, ignore_index=True)
    return df

## detail 만 detail_train으로 저장하기

## coupon list

In [6]:
coupon_list = pd.merge(coupon_list_test, coupon_list_train, how='outer')

In [7]:
coupon_list_test.shape, coupon_list_train.shape, coupon_list.shape

((310, 24), (19413, 24), (19723, 24))

In [8]:
# 캡슐과 장르 통합 및 명칭 변경
coupon_list['Case'] = coupon_list['CAPSULE_TEXT'] + coupon_list['GENRE_NAME']
coupon_list['Case'] = coupon_list['Case'].apply(lambda x: "HOTEL" if x == 'Guest houseHotel and Japanese hotel' 
                          or x == 'HotelHotel and Japanese hotel'
                          or x == 'Japanese hotelHotel and Japanese hotel'
                          or x == 'Japanse guest houseHotel and Japanese hotel'
                          or x == 'LodgeHotel and Japanese hotel'
                          or x == 'Public hotelHotel and Japanese hotel'
                          or x == 'Resort innHotel and Japanese hotel'
                          or x == 'Vacation rentalHotel and Japanese hotel'
                          else "NAIL" if x == 'Nail and eye salonNail and eye salon'
                          else "HAIR" if x == 'Hair salonHair salon'
                          else "FOOD" if x == 'FoodFood'
                          else "SPA" if x == 'SpaSpa'
                          else "BEAUTY" if x == 'BeautyBeauty'
                          else "CLASS" if x == 'ClassLesson'
                          else "CORRESPONDENCE" if x == 'Correspondence courseLessonClassLesson'
                          else "DELIVERY" if x == 'Delivery serviceDelivery service'
                          else "EVENT" if x == 'EventOther coupon'
                          else "GIFT" if x == 'Gift cardGift card'
                          else "HEALTH" if x == 'Health and medicalHealth and medical'
                          else "LEISURE" if x == 'LeisureLeisure'
                          else "LESSON" if x == 'LessonLesson'
                          else "OTHER" if x == 'OtherOther coupon'
                          else "RELAXATION" if x == 'RelaxationRelaxation'
                          else "WEB" if x == 'Web serviceOther coupon'
                          else 'OTHER'
                          )

In [9]:
# 실판매가 게산
coupon_list['Price'] = coupon_list['CATALOG_PRICE'] - coupon_list['DISCOUNT_PRICE']

In [10]:
# 실판매가 정규화
coupon_list["lnDPRICE"] = np.log1p(coupon_list["Price"])
coupon_list["mDPRICE"] = coupon_list.groupby("CAPSULE_TEXT")["lnDPRICE"].transform(np.mean)
coupon_list["sDPRICE"] = coupon_list.groupby("CAPSULE_TEXT")["lnDPRICE"].transform(np.std)
coupon_list["zprice"] = (coupon_list["lnDPRICE"] - coupon_list["mDPRICE"]) / coupon_list["sDPRICE"]

In [11]:
# 지역명 변경
coupon_list.rename(columns = {"LARGE_AREA_NAME": "spot_large", 
                              "ken_name": "spot_pref", 
                              "SMALL_AREA_NAME": "spot_small"}, inplace=True)

In [12]:
# usable: nan -> 1, 2 -> 0
coupon_list['USABLE_DATE_MON'].replace([0,2,1,np.nan],[0,0,1,1], inplace=True)
coupon_list['USABLE_DATE_TUE'].replace([0,2,1,np.nan],[0,0,1,1], inplace=True)
coupon_list['USABLE_DATE_WED'].replace([0,2,1,np.nan],[0,0,1,1], inplace=True)
coupon_list['USABLE_DATE_THU'].replace([0,2,1,np.nan],[0,0,1,1], inplace=True)
coupon_list['USABLE_DATE_FRI'].replace([0,2,1,np.nan],[0,0,1,1], inplace=True)
coupon_list['USABLE_DATE_SAT'].replace([0,2,1,np.nan],[0,0,1,1], inplace=True)
coupon_list['USABLE_DATE_SUN'].replace([0,2,1,np.nan],[0,0,1,1], inplace=True)
coupon_list['USABLE_DATE_HOLIDAY'].replace([0,2,1,np.nan],[0,0,1,1], inplace=True)
coupon_list['USABLE_DATE_BEFORE_HOLIDAY'].replace([0,2,1,np.nan],[0,0,1,1], inplace=True)

In [13]:
coupon_list.columns

Index(['CAPSULE_TEXT', 'GENRE_NAME', 'PRICE_RATE', 'CATALOG_PRICE',
       'DISCOUNT_PRICE', 'DISPFROM', 'DISPEND', 'DISPPERIOD', 'VALIDFROM',
       'VALIDEND', 'VALIDPERIOD', 'USABLE_DATE_MON', 'USABLE_DATE_TUE',
       'USABLE_DATE_WED', 'USABLE_DATE_THU', 'USABLE_DATE_FRI',
       'USABLE_DATE_SAT', 'USABLE_DATE_SUN', 'USABLE_DATE_HOLIDAY',
       'USABLE_DATE_BEFORE_HOLIDAY', 'spot_large', 'spot_pref', 'spot_small',
       'COUPON_ID_hash', 'Case', 'Price', 'lnDPRICE', 'mDPRICE', 'sDPRICE',
       'zprice'],
      dtype='object')

In [14]:
coupon_list['VALIDPERIOD'] = coupon_list['VALIDPERIOD'].fillna(179)

In [15]:
# coupon_list.drop(labels = ['CAPSULE_TEXT'], axis=1, inplace=True )
# coupon_list.drop(labels = ['sDPRICE'], axis=1, inplace=True )

In [16]:
# coupon_list.drop(labels = ['CAPSULE_TEXT'], axis=1, inplace=True )
# coupon_list.drop(labels = ['GENRE_NAME'], axis=1, inplace=True )
# coupon_list.drop(labels = ['CATALOG_PRICE'], axis=1, inplace=True )
# coupon_list.drop(labels = ['DISCOUNT_PRICE'], axis=1, inplace=True )
# coupon_list.drop(labels = ['DISPFROM'], axis=1, inplace=True )
# coupon_list.drop(labels = ['DISPEND'], axis=1, inplace=True )
# coupon_list.drop(labels = ['VALIDFROM'], axis=1, inplace=True )
# coupon_list.drop(labels = ['VALIDEND'], axis=1, inplace=True )
# coupon_list.drop(labels = ['lnDPRICE'], axis=1, inplace=True )
# coupon_list.drop(labels = ['mDPRICE'], axis=1, inplace=True )
# coupon_list.drop(labels = ['Price'], axis=1, inplace=True )
# coupon_list.drop(labels = ['spot_pref'], axis=1, inplace=True )  # 판단이슈 
# coupon_list.drop(labels = ['spot_small'], axis=1, inplace=True ) # 판단이슈 
# coupon_list.drop(labels = ['spot_large'], axis=1, inplace=True ) # 판단이슈 
# coupon_list.drop(labels = ['large_area_name'], axis=1, inplace=True ) # 판단이슈

In [17]:
coupon_list['usable'] = coupon_list['USABLE_DATE_MON'] + coupon_list['USABLE_DATE_TUE'] + coupon_list['USABLE_DATE_WED'] + coupon_list['USABLE_DATE_MON'] + coupon_list['USABLE_DATE_MON'] + coupon_list['USABLE_DATE_MON'] + coupon_list['USABLE_DATE_MON']

In [18]:
summary_table(coupon_list)

        act           dtype                        name    null   unique
0   19723.0          object                CAPSULE_TEXT     0.0     24.0
1   19723.0          object                  GENRE_NAME     0.0     13.0
2   19723.0           int64                  PRICE_RATE     0.0     71.0
3   19723.0           int64               CATALOG_PRICE     0.0   2435.0
4   19723.0           int64              DISCOUNT_PRICE     0.0   1118.0
5   19723.0  datetime64[ns]                    DISPFROM     0.0    386.0
6   19723.0  datetime64[ns]                     DISPEND     0.0    381.0
7   19723.0           int64                  DISPPERIOD     0.0     18.0
8   13480.0  datetime64[ns]                   VALIDFROM  6243.0    388.0
9   13480.0  datetime64[ns]                    VALIDEND  6243.0    521.0
10  19723.0         float64                 VALIDPERIOD     0.0    180.0
11  19723.0         float64             USABLE_DATE_MON     0.0      2.0
12  19723.0         float64             USABLE_DATE_TUE     0.0      2.0
13  19723.0         float64             USABLE_DATE_WED     0.0      2.0
14  19723.0         float64             USABLE_DATE_THU     0.0      2.0
15  19723.0         float64             USABLE_DATE_FRI     0.0      2.0
16  19723.0         float64             USABLE_DATE_SAT     0.0      2.0
17  19723.0         float64             USABLE_DATE_SUN     0.0      2.0
18  19723.0         float64         USABLE_DATE_HOLIDAY     0.0      2.0
19  19723.0         float64  USABLE_DATE_BEFORE_HOLIDAY     0.0      2.0
20  19723.0          object                  spot_large     0.0      9.0
21  19723.0          object                   spot_pref     0.0     47.0
22  19723.0          object                  spot_small     0.0     55.0
23  19723.0          object              COUPON_ID_hash     0.0  19723.0
24  19723.0          object                        Case     0.0     16.0
25  19723.0           int64                       Price     0.0   3105.0
26  19723.0         float64                    lnDPRICE     0.0   3105.0
27  19723.0         float64                     mDPRICE     0.0     24.0
28  19723.0         float64                     sDPRICE     0.0     24.0
29  19723.0         float64                      zprice     0.0   5988.0
30  19723.0         float64                      usable     0.0      6.0

In [19]:
coupon_list.columns

Index(['CAPSULE_TEXT', 'GENRE_NAME', 'PRICE_RATE', 'CATALOG_PRICE',
       'DISCOUNT_PRICE', 'DISPFROM', 'DISPEND', 'DISPPERIOD', 'VALIDFROM',
       'VALIDEND', 'VALIDPERIOD', 'USABLE_DATE_MON', 'USABLE_DATE_TUE',
       'USABLE_DATE_WED', 'USABLE_DATE_THU', 'USABLE_DATE_FRI',
       'USABLE_DATE_SAT', 'USABLE_DATE_SUN', 'USABLE_DATE_HOLIDAY',
       'USABLE_DATE_BEFORE_HOLIDAY', 'spot_large', 'spot_pref', 'spot_small',
       'COUPON_ID_hash', 'Case', 'Price', 'lnDPRICE', 'mDPRICE', 'sDPRICE',
       'zprice', 'usable'],
      dtype='object')

In [20]:
summary_table(coupon_list)

        act           dtype                        name    null   unique
0   19723.0          object                CAPSULE_TEXT     0.0     24.0
1   19723.0          object                  GENRE_NAME     0.0     13.0
2   19723.0           int64                  PRICE_RATE     0.0     71.0
3   19723.0           int64               CATALOG_PRICE     0.0   2435.0
4   19723.0           int64              DISCOUNT_PRICE     0.0   1118.0
5   19723.0  datetime64[ns]                    DISPFROM     0.0    386.0
6   19723.0  datetime64[ns]                     DISPEND     0.0    381.0
7   19723.0           int64                  DISPPERIOD     0.0     18.0
8   13480.0  datetime64[ns]                   VALIDFROM  6243.0    388.0
9   13480.0  datetime64[ns]                    VALIDEND  6243.0    521.0
10  19723.0         float64                 VALIDPERIOD     0.0    180.0
11  19723.0         float64             USABLE_DATE_MON     0.0      2.0
12  19723.0         float64             USABLE_DATE_TUE     0.0      2.0
13  19723.0         float64             USABLE_DATE_WED     0.0      2.0
14  19723.0         float64             USABLE_DATE_THU     0.0      2.0
15  19723.0         float64             USABLE_DATE_FRI     0.0      2.0
16  19723.0         float64             USABLE_DATE_SAT     0.0      2.0
17  19723.0         float64             USABLE_DATE_SUN     0.0      2.0
18  19723.0         float64         USABLE_DATE_HOLIDAY     0.0      2.0
19  19723.0         float64  USABLE_DATE_BEFORE_HOLIDAY     0.0      2.0
20  19723.0          object                  spot_large     0.0      9.0
21  19723.0          object                   spot_pref     0.0     47.0
22  19723.0          object                  spot_small     0.0     55.0
23  19723.0          object              COUPON_ID_hash     0.0  19723.0
24  19723.0          object                        Case     0.0     16.0
25  19723.0           int64                       Price     0.0   3105.0
26  19723.0         float64                    lnDPRICE     0.0   3105.0
27  19723.0         float64                     mDPRICE     0.0     24.0
28  19723.0         float64                     sDPRICE     0.0     24.0
29  19723.0         float64                      zprice     0.0   5988.0
30  19723.0         float64                      usable     0.0      6.0

In [21]:
# dummy 처리 할 column 명 넣어줌
ls_dummy = ['Case','spot_pref','spot_large','spot_small']

In [22]:
coupon_list = pd.get_dummies(coupon_list, columns = ls_dummy)

In [23]:
# train set과 test set을 다시 분리
coupon_list_train = coupon_list[311:]
coupon_list_test = coupon_list[:310]

# detail

In [24]:
detail_train = pd.read_csv('./coupon_data_project2/coupon_detail_train_translated_en.csv', parse_dates=['I_DATE'])

In [25]:
detail_train.rename(columns = {'I_DATE': 'purchase_date'}, inplace=True)
detail_train.rename(columns = {'SMALL_AREA_NAME': 'resid_small'}, inplace=True)

In [26]:
detail_train.drop(labels = ['ITEM_COUNT'], axis=1, inplace=True)
detail_train.drop(labels = ['PURCHASEID_hash'], axis=1, inplace=True)
detail_train.drop(labels = ['resid_small'], axis=1, inplace=True)
detail_train.drop(labels = ['purchase_date'], axis=1, inplace=True)

In [27]:
detail_train.head()

                       USER_ID_hash                    COUPON_ID_hash
0  d9dca3cb44bab12ba313eaa681f663eb  34c48f84026e08355dc3bd19b427f09a
1  560574a339f1b25e57b0221e486907ed  767673b7a777854a92b73b0934ddfae7
2  560574a339f1b25e57b0221e486907ed  4f3b5b91d9831192557c056022fdc1f2
3  560574a339f1b25e57b0221e486907ed  4f3b5b91d9831192557c056022fdc1f2
4  560574a339f1b25e57b0221e486907ed  4f3b5b91d9831192557c056022fdc1f2

In [28]:
detail_train = pd.merge(detail_train, coupon_list, how='left', on='COUPON_ID_hash')
detail_train = detail_train.merge(user_list, on = 'USER_ID_hash', how = 'outer')

In [29]:
len(detail_train["USER_ID_hash"].unique())

22873

In [30]:
len(np.unique(coupon_list_train.COUPON_ID_hash.values))

19412

## 필요없는 변수 지우기

In [31]:
list(detail_train.columns)

['USER_ID_hash',
 'COUPON_ID_hash',
 'CAPSULE_TEXT',
 'GENRE_NAME',
 'PRICE_RATE',
 'CATALOG_PRICE',
 'DISCOUNT_PRICE',
 'DISPFROM',
 'DISPEND',
 'DISPPERIOD',
 'VALIDFROM',
 'VALIDEND',
 'VALIDPERIOD',
 'USABLE_DATE_MON',
 'USABLE_DATE_TUE',
 'USABLE_DATE_WED',
 'USABLE_DATE_THU',
 'USABLE_DATE_FRI',
 'USABLE_DATE_SAT',
 'USABLE_DATE_SUN',
 'USABLE_DATE_HOLIDAY',
 'USABLE_DATE_BEFORE_HOLIDAY',
 'Price',
 'lnDPRICE',
 'mDPRICE',
 'sDPRICE',
 'zprice',
 'usable',
 'Case_BEAUTY',
 'Case_CLASS',
 'Case_DELIVERY',
 'Case_EVENT',
 'Case_FOOD',
 'Case_GIFT',
 'Case_HAIR',
 'Case_HEALTH',
 'Case_HOTEL',
 'Case_LEISURE',
 'Case_LESSON',
 'Case_NAIL',
 'Case_OTHER',
 'Case_RELAXATION',
 'Case_SPA',
 'Case_WEB',
 'spot_pref_Aichi',
 'spot_pref_Akita',
 'spot_pref_Aomori',
 'spot_pref_Chiba',
 'spot_pref_Ehime',
 'spot_pref_Fukui',
 'spot_pref_Fukuoka',
 'spot_pref_Fukushima',
 'spot_pref_Gifu',
 'spot_pref_Gunma',
 'spot_pref_Hiroshima',
 'spot_pref_Hokkaido',
 'spot_pref_Hyogo',
 'spot_pref_Ibaraki',
 'spot_pref_Ishikawa',
 'spot_pref_Iwate',
 'spot_pref_Kagawa',
 'spot_pref_Kagoshima',
 'spot_pref_Kanagawa',
 'spot_pref_Kochi',
 'spot_pref_Kumamoto',
 'spot_pref_Kyoto',
 'spot_pref_Mie',
 'spot_pref_Miyagi',
 'spot_pref_Miyazaki',
 'spot_pref_Nagano',
 'spot_pref_Nagasaki',
 'spot_pref_Nara',
 'spot_pref_Niigata',
 'spot_pref_Oita',
 'spot_pref_Okayama',
 'spot_pref_Okinawa',
 'spot_pref_Osaka',
 'spot_pref_Saga',
 'spot_pref_Saitama',
 'spot_pref_Shiga',
 'spot_pref_Shimane',
 'spot_pref_Shizuoka',
 'spot_pref_Tochigi',
 'spot_pref_Tokushima',
 'spot_pref_Tokyo',
 'spot_pref_Tottori',
 'spot_pref_Toyama',
 'spot_pref_Wakayama',
 'spot_pref_Yamagata',
 'spot_pref_Yamaguchi',
 'spot_pref_Yamanashi',
 'spot_large_China',
 'spot_large_EastSea',
 'spot_large_Hokkaido',
 'spot_large_Hokushinetsu',
 'spot_large_Kansai',
 'spot_large_Kanto',
 'spot_large_Kyushu-Okinawa',
 'spot_large_Northeast',
 'spot_large_Shikoku',
 'spot_small_Aichi',
 'spot_small_Akasaka,Roppongi,Azabu',
 'spot_small_Akita',
 'spot_small_Aomori',
 'spot_small_Chiba',
 'spot_small_Ebisu,MeguroShinagawa',
 'spot_small_Ehime',
 'spot_small_Fukui',
 'spot_small_Fukuoka',
 'spot_small_Fukushima',
 'spot_small_Gifu',
 'spot_small_GinzaShinbashi,Tokyo,Ueno',
 'spot_small_Gunma',
 'spot_small_Hiroshima',
 'spot_small_Hokkaido',
 'spot_small_Hyogo',
 'spot_small_Ibaraki',
 'spot_small_IkebukuroKagurazaka-Akabane',
 'spot_small_Ishikawa',
 'spot_small_Iwate',
 'spot_small_Kagawa',
 'spot_small_Kagoshima',
 'spot_small_Kawasaki,Shonan-Hakoneother',
 'spot_small_Kochi',
 'spot_small_Kumamoto',
 'spot_small_Kyoto',
 'spot_small_Minamiother',
 'spot_small_Miyagi',
 'spot_small_Miyazaki',
 'spot_small_Much',
 'spot_small_Nagano',
 'spot_small_Nagasaki',
 'spot_small_Nara',
 'spot_small_Niigata',
 'spot_small_Northern',
 'spot_small_Okayama',
 'spot_small_Okinawa',
 'spot_small_Saga',
 'spot_small_Saitama',
 'spot_small_Shibuya,Aoyama,Jiyugaoka',
 'spot_small_Shiga',
 'spot_small_Shimane',
 'spot_small_Shinjuku,TakadanobabaNakano-Kichijoji',
 'spot_small_Shizuoka',
 'spot_small_TachikawaMachida,Hachiojiother',
 'spot_small_Tochigi',
 'spot_small_Tokushima',
 'spot_small_Tottori',
 'spot_small_Toyama',
 'spot_small_Triple',
 'spot_small_Wakayama',
 'spot_small_Yamagata',
 'spot_small_Yamaguchi',
 'spot_small_Yamanashi',
 'spot_small_Yokohama',
 'REG_DATE',
 'SEX_ID',
 'AGE',
 'WITHDRAW_DATE',
 'PREF_NAME']

In [35]:
del_ls = ['CAPSULE_TEXT','GENRE_NAME','CATALOG_PRICE',
 'DISCOUNT_PRICE', 'DISPFROM','VALIDPERIOD',
 'DISPEND', 'VALIDFROM',
 'VALIDEND', 'usable',
          'USABLE_DATE_MON',
 'USABLE_DATE_TUE',
 'USABLE_DATE_WED',
 'USABLE_DATE_THU',
 'USABLE_DATE_FRI',
 'USABLE_DATE_SAT',
 'USABLE_DATE_SUN',
          'Price',
 'lnDPRICE',
 'mDPRICE',
 'sDPRICE','REG_DATE',
 'SEX_ID',
 'AGE',
 'WITHDRAW_DATE',
 'PREF_NAME']
train = detail_train.drop(del_ls, 1)
train = detail_train.drop(del_ls, 1)

In [36]:
summary_table(train)

,act,dtype,name,null,unique
0,169087.0,object,USER_ID_hash,0.0,22873.0
1,168996.0,object,COUPON_ID_hash,91.0,19369.0
2,168996.0,float64,PRICE_RATE,91.0,72.0
3,168996.0,float64,DISPPERIOD,91.0,19.0
4,168996.0,float64,USABLE_DATE_HOLIDAY,91.0,3.0
5,168996.0,float64,USABLE_DATE_BEFORE_HOLIDAY,91.0,3.0
6,168996.0,float64,zprice,91.0,5913.0
7,168996.0,float64,Case_BEAUTY,91.0,3.0
8,168996.0,float64,Case_CLASS,91.0,3.0
9,168996.0,float64,Case_DELIVERY,91.0,3.0
10,168996.0,float64,Case_EVENT,91.0,3.0
11,168996.0,float64,Case_FOOD,91.0,3.0
12,168996.0,float64,Case_GIFT,91.0,3.0
13,168996.0,float64,Case_HAIR,91.0,3.0
14,168996.0,float64,Case_HEALTH,91.0,3.0
15,168996.0,float64,Case_HOTEL,91.0,3.0
16,168996.0,float64,Case_LEISURE,91.0,3.0
17,168996.0,float64,Case_LESSON,91.0,3.0
18,168996.0,float64,Case_NAIL,91.0,3.0
19,168996.0,float64,Case_OTHER,91.0,3.0
20,168996.0,float64,Case_RELAXATION,91.0,3.0
21,168996.0,float64,Case_SPA,91.0,3.0
22,168996.0,float64,Case_WEB,91.0,3.0
23,168996.0,float64,spot_pref_Aichi,91.0,3.0
24,168996.0,float64,spot_pref_Akita,91.0,3.0
25,168996.0,float64,spot_pref_Aomori,91.0,3.0
26,168996.0,float64,spot_pref_Chiba,91.0,3.0
27,168996.0,float64,spot_pref_Ehime,91.0,3.0
28,168996.0,float64,spot_pref_Fukui,91.0,3.0
29,168996.0,float64,spot_pref_Fukuoka,91.0,3.0
...,...,...,...,...,...
104,168996.0,float64,spot_small_Kyoto,91.0,3.0
105,168996.0,float64,spot_small_Minamiother,91.0,3.0
106,168996.0,float64,spot_small_Miyagi,91.0,3.0
107,168996.0,float64,spot_small_Miyazaki,91.0,3.0
108,168996.0,float64,spot_small_Much,91.0,3.0
109,168996.0,float64,spot_small_Nagano,91.0,3.0
110,168996.0,float64,spot_small_Nagasaki,91.0,3.0
111,168996.0,float64,spot_small_Nara,91.0,3.0
112,168996.0,float64,spot_small_Niigata,91.0,3.0
113,168996.0,float64,spot_small_Northern,91.0,3.0
114,168996.0,float64,spot_small_Okayama,91.0,3.0
115,168996.0,float64,spot_small_Okinawa,91.0,3.0
116,168996.0,float64,spot_small_Saga,91.0,3.0
117,168996.0,float64,spot_small_Saitama,91.0,3.0
118,168996.0,float64,"spot_small_Shibuya,Aoyama,Jiyugaoka",91.0,3.0
119,168996.0,float64,spot_small_Shiga,91.0,3.0
120,168996.0,float64,spot_small_Shimane,91.0,3.0
121,168996.0,float64,"spot_small_Shinjuku,TakadanobabaNakano-Kichijoji",91.0,3.0
122,168996.0,float64,spot_small_Shizuoka,91.0,3.0
123,168996.0,float64,"spot_small_TachikawaMachida,Hachiojiother",91.0,3.0
124,168996.0,float64,spot_small_Tochigi,91.0,3.0
125,168996.0,float64,spot_small_Tokushima,91.0,3.0
126,168996.0,float64,spot_small_Tottori,91.0,3.0
127,168996.0,float64,spot_small_Toyama,91.0,3.0
128,168996.0,float64,spot_small_Triple,91.0,3.0
129,168996.0,float64,spot_small_Wakayama,91.0,3.0
130,168996.0,float64,spot_small_Yamagata,91.0,3.0
131,168996.0,float64,spot_small_Yamaguchi,91.0,3.0
132,168996.0,float64,spot_small_Yamanashi,91.0,3.0
133,168996.0,float64,spot_small_Yokohama,91.0,3.0

### test 생성

In [37]:
test = coupon_list_test.filter(train.columns)

In [38]:
compare_not_test = [i for i in train.columns if i not in test.columns]
compare_not_train = [i for i in test.columns if i not in train.columns]
print('only_train: {}  \n'.format(compare_not_test))
print('only_test: {}'.format(compare_not_train))

only_train: ['USER_ID_hash']

only_test: []

## 유사도 구하기

In [39]:
train_drop_c = train.drop('COUPON_ID_hash', axis=1)
user = train_drop_c.groupby(by='USER_ID_hash').apply(np.mean)

In [40]:
test_features = test.drop('COUPON_ID_hash', axis=1)
test_features.columns

Index(['PRICE_RATE', 'DISPPERIOD', 'USABLE_DATE_HOLIDAY',
       'USABLE_DATE_BEFORE_HOLIDAY', 'zprice', 'Case_BEAUTY', 'Case_CLASS',
       'Case_DELIVERY', 'Case_EVENT', 'Case_FOOD',
       ...
       'spot_small_Tochigi', 'spot_small_Tokushima', 'spot_small_Tottori',
       'spot_small_Toyama', 'spot_small_Triple', 'spot_small_Wakayama',
       'spot_small_Yamagata', 'spot_small_Yamaguchi', 'spot_small_Yamanashi',
       'spot_small_Yokohama'],
      dtype='object', length=132)

In [48]:
list(user.columns)

['PRICE_RATE',
 'DISPPERIOD',
 'USABLE_DATE_HOLIDAY',
 'USABLE_DATE_BEFORE_HOLIDAY',
 'zprice',
 'Case_BEAUTY',
 'Case_CLASS',
 'Case_DELIVERY',
 'Case_EVENT',
 'Case_FOOD',
 'Case_GIFT',
 'Case_HAIR',
 'Case_HEALTH',
 'Case_HOTEL',
 'Case_LEISURE',
 'Case_LESSON',
 'Case_NAIL',
 'Case_OTHER',
 'Case_RELAXATION',
 'Case_SPA',
 'Case_WEB',
 'spot_pref_Aichi',
 'spot_pref_Akita',
 'spot_pref_Aomori',
 'spot_pref_Chiba',
 'spot_pref_Ehime',
 'spot_pref_Fukui',
 'spot_pref_Fukuoka',
 'spot_pref_Fukushima',
 'spot_pref_Gifu',
 'spot_pref_Gunma',
 'spot_pref_Hiroshima',
 'spot_pref_Hokkaido',
 'spot_pref_Hyogo',
 'spot_pref_Ibaraki',
 'spot_pref_Ishikawa',
 'spot_pref_Iwate',
 'spot_pref_Kagawa',
 'spot_pref_Kagoshima',
 'spot_pref_Kanagawa',
 'spot_pref_Kochi',
 'spot_pref_Kumamoto',
 'spot_pref_Kyoto',
 'spot_pref_Mie',
 'spot_pref_Miyagi',
 'spot_pref_Miyazaki',
 'spot_pref_Nagano',
 'spot_pref_Nagasaki',
 'spot_pref_Nara',
 'spot_pref_Niigata',
 'spot_pref_Oita',
 'spot_pref_Okayama',
 'spot_pref_Okinawa',
 'spot_pref_Osaka',
 'spot_pref_Saga',
 'spot_pref_Saitama',
 'spot_pref_Shiga',
 'spot_pref_Shimane',
 'spot_pref_Shizuoka',
 'spot_pref_Tochigi',
 'spot_pref_Tokushima',
 'spot_pref_Tokyo',
 'spot_pref_Tottori',
 'spot_pref_Toyama',
 'spot_pref_Wakayama',
 'spot_pref_Yamagata',
 'spot_pref_Yamaguchi',
 'spot_pref_Yamanashi',
 'spot_large_China',
 'spot_large_EastSea',
 'spot_large_Hokkaido',
 'spot_large_Hokushinetsu',
 'spot_large_Kansai',
 'spot_large_Kanto',
 'spot_large_Kyushu-Okinawa',
 'spot_large_Northeast',
 'spot_large_Shikoku',
 'spot_small_Aichi',
 'spot_small_Akasaka,Roppongi,Azabu',
 'spot_small_Akita',
 'spot_small_Aomori',
 'spot_small_Chiba',
 'spot_small_Ebisu,MeguroShinagawa',
 'spot_small_Ehime',
 'spot_small_Fukui',
 'spot_small_Fukuoka',
 'spot_small_Fukushima',
 'spot_small_Gifu',
 'spot_small_GinzaShinbashi,Tokyo,Ueno',
 'spot_small_Gunma',
 'spot_small_Hiroshima',
 'spot_small_Hokkaido',
 'spot_small_Hyogo',
 'spot_small_Ibaraki',
 'spot_small_IkebukuroKagurazaka-Akabane',
 'spot_small_Ishikawa',
 'spot_small_Iwate',
 'spot_small_Kagawa',
 'spot_small_Kagoshima',
 'spot_small_Kawasaki,Shonan-Hakoneother',
 'spot_small_Kochi',
 'spot_small_Kumamoto',
 'spot_small_Kyoto',
 'spot_small_Minamiother',
 'spot_small_Miyagi',
 'spot_small_Miyazaki',
 'spot_small_Much',
 'spot_small_Nagano',
 'spot_small_Nagasaki',
 'spot_small_Nara',
 'spot_small_Niigata',
 'spot_small_Northern',
 'spot_small_Okayama',
 'spot_small_Okinawa',
 'spot_small_Saga',
 'spot_small_Saitama',
 'spot_small_Shibuya,Aoyama,Jiyugaoka',
 'spot_small_Shiga',
 'spot_small_Shimane',
 'spot_small_Shinjuku,TakadanobabaNakano-Kichijoji',
 'spot_small_Shizuoka',
 'spot_small_TachikawaMachida,Hachiojiother',
 'spot_small_Tochigi',
 'spot_small_Tokushima',
 'spot_small_Tottori',
 'spot_small_Toyama',
 'spot_small_Triple',
 'spot_small_Wakayama',
 'spot_small_Yamagata',
 'spot_small_Yamaguchi',
 'spot_small_Yamanashi',
 'spot_small_Yokohama']

In [52]:
from sklearn.preprocessing import *

In [49]:
user.shape, test_features.shape

((22873, 132), (310, 132))

In [45]:
user = user.fillna(0)

In [50]:
user.isnull().sum() , \
test_features.isnull().sum()

(PRICE_RATE                                          0
 DISPPERIOD                                          0
 USABLE_DATE_HOLIDAY                                 0
 USABLE_DATE_BEFORE_HOLIDAY                          0
 zprice                                              0
 Case_BEAUTY                                         0
 Case_CLASS                                          0
 Case_DELIVERY                                       0
 Case_EVENT                                          0
 Case_FOOD                                           0
 Case_GIFT                                           0
 Case_HAIR                                           0
 Case_HEALTH                                         0
 Case_HOTEL                                          0
 Case_LEISURE                                        0
 Case_LESSON                                         0
 Case_NAIL                                           0
 Case_OTHER                                          0
 Case_RELAXATION                                     0
 Case_SPA                                            0
 Case_WEB                                            0
 spot_pref_Aichi                                     0
 spot_pref_Akita                                     0
 spot_pref_Aomori                                    0
 spot_pref_Chiba                                     0
 spot_pref_Ehime                                     0
 spot_pref_Fukui                                     0
 spot_pref_Fukuoka                                   0
 spot_pref_Fukushima                                 0
 spot_pref_Gifu                                      0
                                                    ..
 spot_small_Kyoto                                    0
 spot_small_Minamiother                              0
 spot_small_Miyagi                                   0
 spot_small_Miyazaki                                 0
 spot_small_Much                                     0
 spot_small_Nagano                                   0
 spot_small_Nagasaki                                 0
 spot_small_Nara                                     0
 spot_small_Niigata                                  0
 spot_small_Northern                                 0
 spot_small_Okayama                                  0
 spot_small_Okinawa                                  0
 spot_small_Saga                                     0
 spot_small_Saitama                                  0
 spot_small_Shibuya,Aoyama,Jiyugaoka                 0
 spot_small_Shiga                                    0
 spot_small_Shimane                                  0
 spot_small_Shinjuku,TakadanobabaNakano-Kichijoji    0
 spot_small_Shizuoka                                 0
 spot_small_TachikawaMachida,Hachiojiother           0
 spot_small_Tochigi                                  0
 spot_small_Tokushima                                0
 spot_small_Tottori                                  0
 spot_small_Toyama                                   0
 spot_small_Triple                                   0
 spot_small_Wakayama                                 0
 spot_small_Yamagata                                 0
 spot_small_Yamaguchi                                0
 spot_small_Yamanashi                                0
 spot_small_Yokohama                                 0
 Length: 132, dtype: int64,
 PRICE_RATE                                          0
 DISPPERIOD                                          0
 USABLE_DATE_HOLIDAY                                 0
 USABLE_DATE_BEFORE_HOLIDAY                          0
 zprice                                              0
 Case_BEAUTY                                         0
 Case_CLASS                                          0
 Case_DELIVERY                                       0
 Case_EVENT                                          0
 Case_FOOD                                           0
 Case_GIFT                                           0
 Case_HAIR                                           0
 Case_HEALTH                                         0
 Case_HOTEL                                          0
 Case_LEISURE                                        0
 Case_LESSON                                         0
 Case_NAIL                                           0
 Case_OTHER                                          0
 Case_RELAXATION                                     0
 Case_SPA                                            0
 Case_WEB                                            0
 spot_pref_Aichi                                     0
 spot_pref_Akita                                     0
 spot_pref_Aomori                                    0
 spot_pref_Chiba                                     0
 spot_pref_Ehime                                     0
 spot_pref_Fukui                                     0
 spot_pref_Fukuoka                                   0
 spot_pref_Fukushima                                 0
 spot_pref_Gifu                                      0
                                                    ..
 spot_small_Kyoto                                    0
 spot_small_Minamiother                              0
 spot_small_Miyagi                                   0
 spot_small_Miyazaki                                 0
 spot_small_Much                                     0
 spot_small_Nagano                                   0
 spot_small_Nagasaki                                 0
 spot_small_Nara                                     0
 spot_small_Niigata                                  0
 spot_small_Northern                                 0
 spot_small_Okayama                                  0
 spot_small_Okinawa                                  0
 spot_small_Saga                                     0
 spot_small_Saitama                                  0
 spot_small_Shibuya,Aoyama,Jiyugaoka                 0
 spot_small_Shiga                                    0
 spot_small_Shimane                                  0
 spot_small_Shinjuku,TakadanobabaNakano-Kichijoji    0
 spot_small_Shizuoka                                 0
 spot_small_TachikawaMachida,Hachiojiother           0
 spot_small_Tochigi                                  0
 spot_small_Tokushima                                0
 spot_small_Tottori                                  0
 spot_small_Toyama                                   0
 spot_small_Triple                                   0
 spot_small_Wakayama                                 0
 spot_small_Yamagata                                 0
 spot_small_Yamaguchi                                0
 spot_small_Yamanashi                                0
 spot_small_Yokohama                                 0
 Length: 132, dtype: int64)

In [53]:
vector_1 = user.copy()
vector_2 = test_features.copy()

vector_1 = scale(vector_1)
vector_1 = pd.DataFrame(data = vector_1, index = user.index, columns = user.columns )

vector_2 = scale(vector_2)
vector_2 = pd.DataFrame(data = vector_2, index = test_features.index, columns = test_features.columns )

In [54]:
w = [0,1,0,0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5]

In [55]:
for i in range(len(w)):
    vector_1[vector_1.columns[i]] = w[i]*vector_1[vector_1.columns[i]]

In [56]:
for i in range(len(w)):
    vector_2[vector_2.columns[i]] = w[i]*vector_2[vector_2.columns[i]]

In [58]:
from scipy import spatial
def cosine_similarity(vector_1, vector_2):

    return 1 - spatial.distance.cosine(vector_1, vector_2)

In [59]:
matrix = []
for idx1 in tqdm(range(len(user))):
    
    row = []
    for idx2 in range(len(test_features)):
        row.append(cosine_similarity(vector_1.iloc[idx1], vector_2.iloc[idx2]))
    matrix.append(row)

 50%|████▉     | 11373/22873 [22:42<22:57,  8.35it/s]

KeyboardInterrupt:

In [66]:
coupons_ids = test['COUPON_ID_hash']
result_index = vector_1.index
result_columns = [coupons_ids[i] for i in range(0, 310)]
result_df = pd.DataFrame(index= result_index, columns=result_columns,data=matrix)

In [67]:
submission = pd.DataFrame(columns=['USER_ID_hash','PURCHASED_COUPONS'])
submission['USER_ID_hash'] = result_df.index
submission['PURCHASED_COUPONS'] = result_df.T.apply(lambda x: " ".join(x.sort_values(ascending=False)[:11].index)).values

In [68]:
submission.to_csv('cosine_w.csv',index = False,header=True)

In [69]:
list(vector_1.columns)

['PRICE_RATE',
 'DISPPERIOD',
 'zprice',
 'CAPSULE_TEXT_Beauty',
 'CAPSULE_TEXT_Class',
 'CAPSULE_TEXT_Correspondence course',
 'CAPSULE_TEXT_Delivery service',
 'CAPSULE_TEXT_Event',
 'CAPSULE_TEXT_Food',
 'CAPSULE_TEXT_Gift card',
 'CAPSULE_TEXT_Guest house',
 'CAPSULE_TEXT_Hair salon',
 'CAPSULE_TEXT_Health and medical',
 'CAPSULE_TEXT_Hotel',
 'CAPSULE_TEXT_Japanese hotel',
 'CAPSULE_TEXT_Japanse guest house',
 'CAPSULE_TEXT_Leisure',
 'CAPSULE_TEXT_Lesson',
 'CAPSULE_TEXT_Lodge',
 'CAPSULE_TEXT_Nail and eye salon',
 'CAPSULE_TEXT_Other',
 'CAPSULE_TEXT_Public hotel',
 'CAPSULE_TEXT_Relaxation',
 'CAPSULE_TEXT_Resort inn',
 'CAPSULE_TEXT_Spa',
 'CAPSULE_TEXT_Vacation rental',
 'CAPSULE_TEXT_Web service',
 'spot_pref_Aichi',
 'spot_pref_Akita',
 'spot_pref_Aomori',
 'spot_pref_Chiba',
 'spot_pref_Ehime',
 'spot_pref_Fukui',
 'spot_pref_Fukuoka',
 'spot_pref_Fukushima',
 'spot_pref_Gifu',
 'spot_pref_Gunma',
 'spot_pref_Hiroshima',
 'spot_pref_Hokkaido',
 'spot_pref_Hyogo',
 'spot_pref_Ibaraki',
 'spot_pref_Ishikawa',
 'spot_pref_Iwate',
 'spot_pref_Kagawa',
 'spot_pref_Kagoshima',
 'spot_pref_Kanagawa',
 'spot_pref_Kochi',
 'spot_pref_Kumamoto',
 'spot_pref_Kyoto',
 'spot_pref_Mie',
 'spot_pref_Miyagi',
 'spot_pref_Miyazaki',
 'spot_pref_Nagano',
 'spot_pref_Nagasaki',
 'spot_pref_Nara',
 'spot_pref_Niigata',
 'spot_pref_Oita',
 'spot_pref_Okayama',
 'spot_pref_Okinawa',
 'spot_pref_Osaka',
 'spot_pref_Saga',
 'spot_pref_Saitama',
 'spot_pref_Shiga',
 'spot_pref_Shimane',
 'spot_pref_Shizuoka',
 'spot_pref_Tochigi',
 'spot_pref_Tokushima',
 'spot_pref_Tokyo',
 'spot_pref_Tottori',
 'spot_pref_Toyama',
 'spot_pref_Wakayama',
 'spot_pref_Yamagata',
 'spot_pref_Yamaguchi',
 'spot_pref_Yamanashi',
 'spot_large_China',
 'spot_large_EastSea',
 'spot_large_Hokkaido',
 'spot_large_Hokushinetsu',
 'spot_large_Kansai',
 'spot_large_Kanto',
 'spot_large_Kyushu-Okinawa',
 'spot_large_Northeast',
 'spot_large_Shikoku',
 'spot_small_Aichi',
 'spot_small_Akasaka,Roppongi,Azabu',
 'spot_small_Akita',
 'spot_small_Aomori',
 'spot_small_Chiba',
 'spot_small_Ebisu,MeguroShinagawa',
 'spot_small_Ehime',
 'spot_small_Fukui',
 'spot_small_Fukuoka',
 'spot_small_Fukushima',
 'spot_small_Gifu',
 'spot_small_GinzaShinbashi,Tokyo,Ueno',
 'spot_small_Gunma',
 'spot_small_Hiroshima',
 'spot_small_Hokkaido',
 'spot_small_Hyogo',
 'spot_small_Ibaraki',
 'spot_small_IkebukuroKagurazaka-Akabane',
 'spot_small_Ishikawa',
 'spot_small_Iwate',
 'spot_small_Kagawa',
 'spot_small_Kagoshima',
 'spot_small_Kawasaki,Shonan-Hakoneother',
 'spot_small_Kochi',
 'spot_small_Kumamoto',
 'spot_small_Kyoto',
 'spot_small_Minamiother',
 'spot_small_Miyagi',
 'spot_small_Miyazaki',
 'spot_small_Much',
 'spot_small_Nagano',
 'spot_small_Nagasaki',
 'spot_small_Nara',
 'spot_small_Niigata',
 'spot_small_Northern',
 'spot_small_Okayama',
 'spot_small_Okinawa',
 'spot_small_Saga',
 'spot_small_Saitama',
 'spot_small_Shibuya,Aoyama,Jiyugaoka',
 'spot_small_Shiga',
 'spot_small_Shimane',
 'spot_small_Shinjuku,TakadanobabaNakano-Kichijoji',
 'spot_small_Shizuoka',
 'spot_small_TachikawaMachida,Hachiojiother',
 'spot_small_Tochigi',
 'spot_small_Tokushima',
 'spot_small_Tottori',
 'spot_small_Toyama',
 'spot_small_Triple',
 'spot_small_Wakayama',
 'spot_small_Yamagata',
 'spot_small_Yamaguchi',
 'spot_small_Yamanashi',
 'spot_small_Yokohama']